


app:
  topic:
    serialized: serializedproducer
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: com.example.lab3.serializedproducer.producer.serializer.EmployeeSerializer